- hosts: deploy_server
  become: yes
  tasks:

    - name: Stop old container if exists
      shell: |
        docker stop project9 || true
        docker rm project9 || true

    - name: Pull latest docker image
      shell: docker pull sky91win/project9:latest

    - name: Run new container
      shell: docker run -d --name project9 -p 80:80 sky91win/project9:latest
